project:
  type: website
  output-dir: docs

website:
  title: "Visualización Analítica"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca de
      - href: viz.qmd
        text: Visualización

format:
  html:
    theme: cosmo
    toc: true
