project:
  type: website
  output-dir: docs

website:
  title: "Visualización Analítica"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca de
      - href: viz.qmd
        text: Visualización
      - href: univariate.qmd
        text: Analisis Univariado
      - href: bivariate.qmd
        text: Analisis Bivariado

format:
  html:
    theme: sandstone
    toc: true
